[package]
name = "xtask"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
cargo_metadata = "0.18"
clap = { workspace = true, features = ["derive"] }
proc-macro2 = "1"
syn = { version = "3", features = ["full", "visit"] }

[dev-dependencies]
tempfile = { workspace = true }
