[package]
name = "venom-examples"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
clap.workspace = true
tokio.workspace = true
url = "2.5"
venom-scanner = { version = "0.10.0-alpha.1", path = "../crates/venom-scanner", default-features = false, features = ["legacy-scanner", "distributed", "plugins"] }

[[bin]]
name = "basic_scan"
path = "basic_scan.rs"

[[bin]]
name = "custom_plugin"
path = "custom_plugin.rs"

[[bin]]
name = "distributed_scan"
path = "distributed_scan.rs"

[[bin]]
name = "decision_scan"
path = "decision_scan.rs"

[[bin]]
name = "api_visibility_review"
path = "api_visibility_review.rs"
