//! INFO-only starter for Venom's source-level plugin trait boundary.

use async_trait::async_trait;
use venom_scanner::{
    EvidenceKind, EvidenceValue, KnowledgePredicate, Plugin, PluginCategory, PluginContext,
    PluginError, PluginObservation,
};

/// Exact inert input used only to exercise the generated trait implementation.
pub const TRAIT_FIXTURE_MARKER: &[u8] = b"venom-plugin-fixture-marker";

/// Starter trait fixture generated by the Venom plugin template.
///
/// This type is not a detector and makes no security claim.
pub struct GeneratedPlugin;

#[async_trait]
impl Plugin for GeneratedPlugin {
    fn id(&self) -> &str {
        "{{ plugin_id }}"
    }

    fn name(&self) -> &str {
        "{{ project-name }}"
    }

    fn version(&self) -> &str {
        env!("CARGO_PKG_VERSION")
    }

    fn description(&self) -> &str {
        "Trait-boundary observation fixture: {{ plugin_description }}"
    }

    fn author(&self) -> &str {
        env!("CARGO_PKG_AUTHORS")
    }

    fn category(&self) -> PluginCategory {
        PluginCategory::Custom
    }

    async fn execute(&self, context: &PluginContext) -> Result<(), PluginError> {
        if context.input() != TRAIT_FIXTURE_MARKER {
            return Ok(());
        }

        let predicate = KnowledgePredicate::new("plugin.fixture", "generated_marker")
            .map_err(|_| PluginError::InvalidConfig("fixture predicate is invalid".to_owned()))?;
        context.record(PluginObservation::new(
            EvidenceKind::Custom("plugin.fixture.marker".to_owned()),
            predicate,
            EvidenceValue::Text(
                "INFO observation: generated plugin exercised the Plugin trait boundary; no security claim"
                    .to_owned(),
            ),
            "trait-boundary",
        )?)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use venom_scanner::{
        EntityId, PluginConfig, PluginExecutionRequest, PluginHttpRequest, PluginHttpResponse,
        PluginRegistry, PluginRequestBroker,
    };

    struct NoIoBroker;

    #[async_trait]
    impl PluginRequestBroker for NoIoBroker {
        async fn execute(
            &self,
            _request: PluginHttpRequest,
        ) -> Result<PluginHttpResponse, PluginError> {
            Err(PluginError::BrokerFailure(
                "the generated trait fixture grants no transport authority".to_owned(),
            ))
        }
    }

    fn request(input: &[u8]) -> PluginExecutionRequest {
        let origin = "https://example.test/".parse().expect("valid test origin");
        PluginExecutionRequest::new(
            EntityId::new("authorized-origin:generated-plugin").expect("valid subject"),
            origin,
            "case:generated-plugin",
            Arc::new(NoIoBroker),
        )
        .expect("valid request")
        .with_input(input.to_vec())
        .expect("bounded fixture input")
    }

    #[tokio::test]
    async fn records_only_the_info_trait_boundary_observation() {
        let registry = PluginRegistry::new();
        registry
            .register(Arc::new(GeneratedPlugin), PluginConfig::default())
            .expect("fixture registration succeeds");

        let receipt = registry
            .execute("{{ plugin_id }}", request(TRAIT_FIXTURE_MARKER))
            .await
            .expect("fixture execution succeeds");
        assert_eq!(receipt.observations().len(), 1);
        assert_eq!(receipt.usage().requests(), 0);
        assert_eq!(
            receipt.observations()[0].predicate().dotted(),
            "plugin.fixture.generated_marker"
        );

        let no_match = registry
            .execute("{{ plugin_id }}", request(b"different inert input"))
            .await
            .expect("non-marker execution succeeds");
        assert!(no_match.observations().is_empty());
    }
}
